development:
  adapter: postgresql
  database: covid19_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: covid19_dev
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: covid19_prod
  pool: 5
  timeout: 5000